### ISSUE TITLE
pm2 module infine loop and restarting

### ISSUE THREAD

**Issue by Productivix** [vmarchaud/pm2-githook#18]
hi, 
thanks for this idea but there is a problem.
I have installed this last 1.11 version on a windows 10 pc
pm2 runs well , but this module restarts with errors in loop : here is the error log attached (if you let it 2 mn, it becomes huge)
[pm2-githook-error.log](https://github.com/vmarchaud/pm2-githook/files/8098137/pm2-githook-error.log)

thanks !

**Comment by vmarchaud** [comment]
This is because your configuration isn't a valid json: https://github.com/vmarchaud/pm2-githook/blob/master/index.js#L48

**Comment by Productivix** [comment]
ok thks I will check and keep posted - pbs to inject as documented : 
"pm2 set pm2-githook:apps "{\"APP_NAME\":{\"secret\":\"supersecret\",\"prehook\":\"npm install --production && git submodule update --init\",\"posthook\":\"echo done\",\"errorhook\":\"echo error\"}}"
"
only {\"APP_NAME\":{\"secret\":\"supersecret\",\"prehook\":\"npm install --production remains in the config ,

**Comment by vmarchaud** [comment]
> be after the pm2 does not take the good version

I've stopped working with PM2 a while ago, they might have changed something on how this `set` command. I would advise to edit the config file directly indeed.

**Comment by Productivix** [comment]
hello , 
thank you for your answer .

I have edited the .pm2/module_conf.json myself as much as I can with the doc , and put : 
```

{
    "pm2-githook": {
        "apps": {"myapp":
            {
            "secret":"1234",
            "prehook":"npm install --production && git submodule update --init",
            "posthook":"echo done",
            "errorhook":"echo error"}
        },
        "port": 8888
    },
    "module-db-v2": {
        "pm2-githook": {}
    }
```
}
The Github webhook delivery has reached the domain (let say "mydomain") I put to reach the localhost:8888/myapp
but let me the following message : 

"We couldn’t deliver this payload: encountered an unexpected end of file when reading the response

and in /etc/.pm2/log/pm2-githook-error.log , I get: 
```

SyntaxError: Unexpected token p in JSON at position 0
    at JSON.parse (<anonymous>)
    at Worker.checkRequest (C:\etc\.pm2\modules\pm2-githook\node_modules\pm2-githook\index.js:277:23)
    at Worker.processRequest (C:\etc\.pm2\modules\pm2-githook\node_modules\pm2-githook\index.js:106:20)
    at IncomingMessage.<anonymous> (C:\etc\.pm2\modules\pm2-githook\node_modules\pm2-githook\index.js:88:10)
    at IncomingMessage.emit (node:events:532:35)
    at IncomingMessage.emit (node:domain:475:12)
    at endReadableNT (node:internal/streams/readable:1346:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
(node:13868) Warning: Accessing non-existent property 'cat' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
(node:13868) Warning: Accessing non-existent property 'cd' of module exports inside circular dependency
(node:13868) Warning: Accessing non-existent property 'chmod' of module exports inside circular dependency
(node:13868) Warning: Accessing non-existent property 'cp' of module exports inside circular dependency
(node:13868) Warning: Accessing non-existent property 'dirs' of module exports inside circular dependency
(node:13868) Warning: Accessing non-existent property 'pushd' of module exports inside circular dependency
(node:1386 ...
```
the Nginx error.log of the domain I put, have logged : 
2022/02/23 14:47:48 [error] 2856#15288: *52 WSARecv() failed (10054: An existing connection was forcibly closed by the remote host) while reading upstream, client: 140.82.115.99, server: mydomain, request: "POST /myapp HTTP/1.1"

do you have an idea where is it comming from please ?
thanks !

**Comment by Productivix** [comment]
I think I have more to configure with help of https://docs.github.com/en/developers/webhooks-and-events/webhooks/creating-webhooks

but, at this step, do you think that my config is ok please to answer to pull Webhook from Github ?

**Comment by Productivix** [comment]
hi, you speak of 'graceful reload' of pm2 : this has been droped for a long time . What is the replacement ?
what do you use at the place of pme2-githook so ?

**Comment by Productivix** [comment]
Hello, oui j'avais bien vu que tu étais Français à ton nom. Pas forcément plus facile mais plus limité en participation de communauté après !

Mais j'utilise le module en local et tout est en local mais cela ne donne pas plus que ce que j'ai mis. 
// I use the module in local and and it does not give more infos that I wrote.

It is a very useful module. May be the doc has to be enhanced . I continue to test.

**Comment by vmarchaud** [comment]
> Hello, oui j'avais bien vu que tu étais Français à ton nom. Pas forcément plus facile mais plus limité en participation de communauté après !

:+1:

> It is a very useful module. May be the doc has to be enhanced . I continue to test.

Feel free to make improvement and open PRs, even i don't make update it myself i'm happy to accept any contribution !

**Comment by Productivix** [comment]
hi, I find the problems (it is may be a "PR")
to reproduce and diags : (on windows but may be similar on linux)

1/ you install your module , with the last pm2 version , 
2/ I type under the right directory : 
C:\etc\.pm2\modules\pm2-githook\node_modules>node --trace-warnings pm2-githook
I get : the attached errors that may help you to upgrade / recompile your module 

[220224-circular-errors.txt](https://github.com/vmarchaud/pm2-githook/files/8133873/220224-circular-errors.txt)

3/ then , I did the 2 commands , and get :

--> C:\etc\.pm2\modules\pm2-githook\node_modules>npm i
up to date, audited 238 packages in 7s
4 packages are looking for funding
  run `npm fund` for details

7 vulnerabilities (4 moderate, 3 high)

Some issues need review, and may require choosing
a different dependency.

Run `npm audit` for details.

--> C:\etc\.pm2\modules\pm2-githook\node_modules>npm audit
# npm audit report

glob-parent  <5.1.2
Severity: high
Regular expression denial of service - https://github.com/advisories/GHSA-ww39-953v-wcq6
No fix available
node_modules/glob-parent
  chokidar  1.0.0-rc1 - 2.1.8
  Depends on vulnerable versions of glob-parent
  node_modules/chokidar
    pm2  0.12.0 - 4.3.1
    Depends on vulnerable versions of chokidar
    Depends on vulnerable versions of mkdirp
    Depends on vulnerable versions of shelljs
    node_modules/pm2
      pm2-githook  *
      Depends on vulnerable versions of pm2
      node_modules/pm2-githook

minimist  <0.2.1
Severity: moderate
Prototype Pollution in minimist - https://github.com/advisories/GHSA-vh95-rmgr-6w4m
No fix available
node_modules/minimist
  mkdirp  0.4.1 - 0.5.1
  Depends on vulnerable versions of minimist
  node_modules/mkdirp
    pm2  0.12.0 - 4.3.1
    Depends on vulnerable versions of chokidar
    Depends on vulnerable versions of mkdirp
    Depends on vulnerable versions of shelljs
    node_modules/pm2
      pm2-githook  *
      Depends on vulnerable versions of pm2
      node_modules/pm2-githook

shelljs  <0.8.5
Severity: moderate
Improper Privilege Management in shelljs - https://github.com/advisories/GHSA-64g7-mvw6-v9qj
No fix available
node_modules/shelljs
  pm2  0.12.0 - 4.3.1
  Depends on vulnerable versions of chokidar
  Depends on vulnerable versions of mkdirp
  Depends on vulnerable versions of shelljs
  node_modules/pm2
    pm2-githook  *
    Depends on vulnerable versions of pm2
    node_modules/pm2-githook

7 vulnerabilities (4 moderate, 3 high)

Some issues need review, and may require choosing
a different dependency.


--> Are you still able to recompile an up-to-date package please ? 
thank you per advance !

**Comment by Productivix** [comment]
In fact this module scrap the pm2 install : 
if you do : npm install pm2 -g
and then pm2 install pm2-githook , 
if you do pm2 --version , you will get the last one but npm i  will result in "7 vulnerabilities (4 moderate, 3 high) "
you need to do again npm install pm2 -g to recover a stable version

**Comment by vmarchaud** [comment]
It might be because this module depend on a older pm2 version (https://github.com/vmarchaud/pm2-githook/blob/master/package.json#L37), i might get fixed if we bump pm2 to the latest

**Comment by Productivix** [comment]
excuses, je n'ai pas compris si on avait qq chose à faire ou si vous republiez une nouvelle version ?

**Comment by vmarchaud** [comment]
> excuses, je n'ai pas compris si on avait qq chose à faire ou si vous republiez une nouvelle version ?

Tu peux essayer avec une version locale voir ca regle le soucis ? Si tu git clone, update le package.json avec la derniere version de pm2 et que tu fait `pm2 install .` est-ce que ca marche ?

**Comment by Productivix** [comment]
Ok : what works with package.json modification + something in pm2 that I do not master: (I did that process 3 times with same good result)

- git clone --recurse-submodules https://github.com/vmarchaud/pm2-githook.git
- I am under .pm2/modules, I do a cd pm2-githook
- I change all the dependencies with last versions : 
`"dependencies": {
    "async": "^3.2.3",
    "ipaddr.js": "^2.0",
    "pm2": "^5.2",
    "pmx": "^1.6.7",
    "vizion": "^2.2.1"
  },`
- then pm2 install .
gives errors and githook stops : here is the error log :
[pm2-githook-error.log](https://github.com/vmarchaud/pm2-githook/files/8162038/pm2-githook-error.log)
 it says that it missed pmx 

so I did : npm i pmx
then : pm2 delete githook 
then : pm2 install .
and githook starts stable 
if I type npm i , I get "found 0 vulnerabilities" (this was not the case before)

so I think that there is 2 things to correct in this pack : 
- the package.json with my listed dependencies
- manage the install by pm2 of those dependencies and mainlly pmx

**Comment by Productivix** [comment]
but with this method, module.conf is not filled up with githook module

**Comment by Productivix** [comment]
hello, I purged my old module install.
I test with $ pm2 install pm2-githook
all is correct : module_conf.json with config, error log empty, , pm2.log : ok

This new version 2 is OK. I very proud to having helped to this improvement, thank you for being so quick in your answers !

**Comment by Productivix** [comment]
I have to make it work now on my installation ;-)  !
