### ISSUE TITLE
Cannot read property 'length' of null

### ISSUE THREAD

**Issue by pedrofracassi** [vmarchaud/pm2-githook#6]
I'm getting this error whenever I push something to my repo:

```
TypeError: Cannot read property 'length' of null
    at Worker.processRequest (/root/.pm2/node_modules/pm2-githook/index.js:101:17)
    at IncomingMessage.<anonymous> (/root/.pm2/node_modules/pm2-githook/index.js:88:10)
    at emitNone (events.js:67:13)
    at IncomingMessage.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:923:12)
    at nextTickCallbackWith2Args (node.js:458:9)
    at process._tickDomainCallback [as _tickCallback] (node.js:413:17)
TypeError: Cannot read property 'length' of null
    at Worker.processRequest (/root/.pm2/node_modules/pm2-githook/index.js:101:17)
    at IncomingMessage.<anonymous> (/root/.pm2/node_modules/pm2-githook/index.js:88:10)
    at emitNone (events.js:67:13)
    at IncomingMessage.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:923:12)
    at nextTickCallbackWith2Args (node.js:458:9)
    at process._tickDomainCallback [as _tickCallback] (node.js:413:17)
```

**Comment by pedrofracassi** [comment]
Ok, forget it, this is what I was doing wrong:

![image](https://cloud.githubusercontent.com/assets/25179120/25551950/395c94a2-2c64-11e7-8be5-27c5949f8fb5.png)

The right way to do it is:
![image](https://cloud.githubusercontent.com/assets/25179120/25551943/0e5097a4-2c64-11e7-8956-19dc88ea4474.png)
